import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Footer';
import classNames from '@/helpers/classNames';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={classNames(inter.className, 'flex flex-col min-h-screen')}
      >
        <main className="flex-grow mx-auto max-w-7xl sm:px-6 lg:px-8 mt-10">
          {children}
        </main>
        <Footer className="" />
      </body>
    </html>
  );
}
